### PR TITLE
Bump to 3.4.1

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
@BFH-ktt1 do you know how I can manually download the files instead of making `gradlew` download everything itself? The sandbox doesn't allow network access when in the building process.

**Comment by BFH-ktt1** [comment]
@TheEvilSkeleton , I guess that the flatpak package was depending on the jar file. I added it to the v3.4.1 release, and will add it also to the future releases, hope this helps.

**Comment by TheEvilSkeleton** [comment]
@BFH-ktt1 that helps a lot.

I'd still like to know if there's a way to download dependencies *before* the building steps, so the `./gradlew` command will automatically use https://services.gradle.org/distributions/gradle-6.3-bin.zip instead of downloading it when running.

**Comment by BFH-ktt1** [comment]
@TheEvilSkeleton , gradle will not only download the https://services.gradle.org/distributions/gradle-6.3-bin.zip, but when building it will also clone all the maven repositories on which logisim depends. So the way to go here is by the .jar file I guess.

**Pull request merged**
