### PR TITLE
Add WM support

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
Convenient fix for https://github.com/flathub/com.github.reds.LogisimEvolution/issues/2.

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
@tinywrkb can you check if this works for you? You mentioned this flag a year ago in https://github.com/flathub/flathub/pull/1951#issuecomment-735912173, so I'd like to know if this works without a problem in a WM (without you manually setting the variable with Flatseal or `flatpak override`).

**Comment by tinywrkb** [comment]
@TheEvilSkeleton your assumption that `XDG_CURRENT_DESKTOP` is empty, but that might not be the case.

Currently, `/usr/share/xdg-desktop-portal/portals/wlr.portal` has `UseIn=wlroots;sway;Wayfire;river`, so the test should be similar to the following.

```
case "${XDG_CURRENT_DESKTOP}:" in
  :|wlroots:*|sway:*|Wayfire:*|river:*)
  export "_JAVA_AWT_WM_NONREPARENTING=1"
  ;;
esac 
```
Note that you can switch the interpreter to bourne shell (/bin/sh).  
And yes, `_JAVA_AWT_WM_NONREPARENTING=1` is still required with Sway 1.7 and wlroots 0.15.0.

**Comment by TheEvilSkeleton** [comment]
Thanks.

**Comment by tinywrkb** [comment]
Works correctly with Sway 1.7 and `_JAVA_AWT_WM_NONREPARENTING` set by the wrapper.  

I'm not convinced that this is the place to set the var.  

This seems to be a Java AWT bug, so it shouldn't be worked around in applications and packaging. Maybe this issue will get a proper fix now that the devs finally started working on Wayland support in JDK.  

It will be a maintenance chore to maintain and keep with `XDG_CURRENT_DESKTOP` values. If I understand correctly, this issue also manifests with some X11 WMs, though I believe that with X11 WMs it's unusual that `XDG_CURRENT_DESKTOP` would be set.

Would this introduce a regression with some WM? X11 WMs, Chrome OS, WSL2.  

IMO if `_JAVA_AWT_WM_NONREPARENTING` should be set anywhere, then it should be the WM environment, and not by the application.

**Comment by TheEvilSkeleton** [comment]
> IMO if `_JAVA_AWT_WM_NONREPARENTING` should be set anywhere, then it should be in the WM environment, and not by the application.

Good point, that just changed my mind on this MR. I'm going to close this. Thanks!

**Pull request closed without merging**
